### ISSUE TITLE
Class 'BeyondCode\DumpServer\DumpServerServiceProvider' not found

### ISSUE THREAD

**Issue by nucreativa** [GoogleCloudPlatform/php-docs-samples#736]
I try to install Laravel 5.7 but i always got error `"Class 'BeyondCode\DumpServer\DumpServerServiceProvider' not found". `
Its new on Laravel 5.7, and already on composer.json but why it can't be load?

its my composer.json
```
{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": "7.2.*",
        "fideloper/proxy": "^4.0",
        "google/cloud": "^0.82.0",
        "laravel/framework": "5.7.*",
        "laravel/tinker": "^1.0"
    },
    "require-dev": {
        "beyondcode/laravel-dump-server": "^1.2",
        "filp/whoops": "^2.0",
        "fzaninotto/faker": "^1.4",
        "mockery/mockery": "^1.0",
        "nunomaduro/collision": "^2.0",
        "phpunit/phpunit": "^7.0"
    },
    "autoload": {
        "classmap": [
            "database/seeds",
            "database/factories"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "extra": {
        "laravel": {
            "dont-discover": [
            ]
        }
    },
    "scripts": {
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate"
        ],
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover"
        ],
        "post-install-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postInstall",
            "chmod -R 755 bootstrap\/cache"
        ],
        "post-update-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postUpdate",
            "chmod -R 755 bootstrap\/cache"
        ],
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}

```

**Comment by flashadvocate** [comment]
Yep, this is actually what I had to do as well.

**Comment by taliptako** [comment]
This is my issue just clean laravel installation with app.yaml env values
php artisan package:discover doesnt work
```
File upload done.
Updating service [default]...failed.                                                                                                                                                                               
ERROR: (gcloud.app.deploy) Error Response: [9] Cloud build 0c3fe336-8669-416f-9bcd-26c8053874ed status: FAILURE.
Build error details: {"message": "`composer_update_lock` had stderr output:\nDo not run Composer as root/super user! See https://getcomposer.org/root for details\nLoading composer repositories with package information\nUpdating dependencies (including require-dev)\nPackage operations: 71 installs, 0 updates, 0 removals\n  - Installing vlucas/phpdotenv (v2.5.1): Downloading (connecting...)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (0%)           \b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (15%)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (30%)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (100%)\n  - Installing symfony/css-selector (v4.1.7): Downloading (connecting...)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (0%)           \b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (5%)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (10%)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (15%)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (20%)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (30%)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (35%)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (40%)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (45%)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (50%)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (55%)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (60%)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (65%)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (70%)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (75%)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (80%)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (85%)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (90%)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (95%)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (100%)\n  - Installing tijsverkoyen/css-to-inline-styles (2.2.1): Downloading (connecting...)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (0%)           \b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (40%)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (80%)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (100%)\n  - Installing symfony/polyfill-php72 (v1.10.0): Downloading (connecting...)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (0%)           \b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (80%)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (100%)\n  - Installing symfony/polyfill-mbstring (v1.10.0): Downloading (connecting...)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (0%)           \b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (30%)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (55%)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (100%)\n  - Installing symfony/var-dumper (v4.1.7): Downloading (connecting...)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (0%)           \b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (5%)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (15%)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (20%)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (25%)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (30%)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (40%)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (45%)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (50%)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (60%)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (65%)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (70%)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (75%)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (80%)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (85%)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (95%)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (100%)\n  - Installing symfony/routing (v4.1.7): Downloading (connecting...)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (0%)           \b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (5%)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (10%)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (15%)\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\bDownloading (20%)\b\b\b\b.

```

**Comment by PrimeException** [comment]
The correct solution is to run:
php artisan config:clear

This will be resolved when GCP stops installing dev dependencies in production with the --no-dev flag.

**Comment by dxhans5** [comment]
> The correct solution is to run:
> php artisan config:clear

Running that command created the same error:
![image](https://user-images.githubusercontent.com/1097143/50647432-c38d2000-0f35-11e9-9521-6b264de326b3.png)

**Comment by bshaffer** [comment]
I had to include `beyondcode/laravel-dump-server` in the `require` section, as I have been installing production dependencies with `composer require --no-dev`.

Can anyone explain to me why a dev dependency is required in production? I may have confugred something wrong.

**Comment by PrimeException** [comment]
There is a bug in "update-vendor-directory" in app engine that runs
composer update and installs development dependencies regardless of
settings.

You should never update production code, that's why the lock file exists.

The build script needs to be changed from "composer update" to "composer
install --no-dev"

I submitted a bug report and they claimed that updating and installing
development dependencies in production is intended behavior.

They clearly have no idea what they're doing.

**Comment by bshaffer** [comment]
@PrimeException I now understand the issue better, after talking to someone on the project. The App Engine build server installs dev dependencies so that if scripts need to be run which are not used in production, the dev dependencies are there. 

Because Laravel creates `bootstrap/cache/services.php` as part of the `artisan package:discover` command, the `beyondcode/laravel-dump-server` package is discovered, loaded into `services.php`, and then fails to load in production.

So the good news is, your dev dependencies are NOT being loaded into production. The bad news is, your `services.php` file inaccurately reflects the dependencies loaded into the Cloud Build environment.

The best workaround is to run `composer remove --dev beyondcode/laravel-dump-server`. A more complete workaround would be to add the following to `composer.json`:

```json
{
    // ...
    "scripts": {
            // ...
            "gcp-build": [
                "composer install --no-dev"
            ]
    }
}
```

This workaround will remove all dev dependencies on the build server.

**Comment by PrimeException** [comment]
Using the flexible environment also resolves the issue because the flexible
environment does not install development dependencies by default, like it's
supposed to.

Development dependencies should never be installed by default and any
workarounds should be to install development dependencies, not prevent
their installation.

This is a bug, regardless if someone "intended" to do it.

**Comment by taliptako** [comment]
@bshaffer Problem here is when deploying to App engine standard we are also including our packages.php and services.php files. These files should be created again in google servers by composer command but they can't because App engine standard has read-only filesystem. Is there any possibility to allow writing to filesystem while composer install command running. 

Otherwise even we run composer install or composer install --no-dev those cache files will be wrong since they are created by our local env ..

**Comment by taliptako** [comment]
@bshaffer To learn more about package:discover command read the Package Discovery section in this article [https://divinglaravel.com/laravels-package-auto-discovery](https://divinglaravel.com/laravels-package-auto-discovery)

If we run composer install in our local those cache files will also contain the dev dependencies and they will be uploaded to app engine which will cause error later..

**Comment by bshaffer** [comment]
@taliptako Package Discovery _is_ run on the build server, and the files do get updated. The problem which we see here is that the Cloud Build server installs **dev** dependencies when running on the build server, which causes `package.php` and `services.php` to contain dev classes which then don't exist in production.

An important note to @PrimeException is that **the dev dependencies are NOT included in the production deployment**. As the Cloud Build environment is a build server and not production, dev dependencies are included in case tools are needed in order to build the app which are not needed in production.

I can recommend to not install dev dependencies in the Cloud Build environment, but I am not convinced this is the correct approach. The easiest approach I have found is to include a composer `gcp-build` script, which gets run in Cloud Build, which removes dev dependencies and runs Package Discovery. That solution, noted above, is to use `composer install --no-dev`. You can add this to your `composer.json` with the following command:

```sh
php -r "file_put_contents('composer.json', json_encode(array_merge_recursive(json_decode(file_get_contents('composer.json'), true), ['scripts' => ['gcp-build' => ['composer install --no-dev']]]), JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));"
```

**Comment by PrimeException** [comment]
The proposed composer.json modification does not work.

Autoload/ClassMapGenerator.php: failed to open stream: No such file or
directory.

I can't believe I attempted to use app engine again after promising my
computer that I would never waste cycles on such garbage again.

DOWN WITH APP ENGINE!
PHP COMMUNITY UNITE!

**Comment by bshaffer** [comment]
I've found another solution. Laravel includes a Composer configuration for ignoring packages in Package Discovery. If you update the `extra.laravel.dont-discover` value to be either `*` or `beyondcode/laravel-dump-server`, the error is resolved:

```json
   "extra": {
        "laravel": {
            "dont-discover": ["beyondcode/laravel-dump-server"]
        }
    },
```

This will mean you cannot run `php artisan dump-server` without removing this line and running package discover again, however.

**Comment by PrimeException** [comment]
The ONLY solution is to stop installing development dependencies in a
production environment.

I'll use the flexible environment until Google decides to fix this bug,
which I doubt will ever be fixed because their app engine TLS
implementation bug for self signed CAs has been reported by 25+ people over
three years and still isn't fixed.

**Comment by bshaffer** [comment]
A fix for this is on the way: https://github.com/GoogleCloudPlatform/runtimes-common/pull/763

This will ensure dev dependencies are not installed in the Cloud Build environment. If dev dependencies are required, use the Composer `gcp-build` script to add them.

**Comment by Snaver** [comment]
Not sure if this problem is directly related to the issue I was facing, but please see my Laravel changes in the following pull request https://github.com/GoogleCloudPlatform/php-docs-samples/pull/833.

**Comment by neorganic** [comment]
For me personally, the fix was:
```
{
    "scripts": {
        "gcp-build": [
            "composer install --no-dev"
        ]
    }
}

```
as @bshaffer  and others noted

**Comment by bushmusi** [comment]
I have deleted **vendor** folder then I reinstall packages using `composer install` ...then it works fine
